### ISSUE TITLE
ValueError: Cannot feed value of shape shape (1, 224, 224, 4) for Tensor 'input_imgs:0',

### ISSUE THREAD

**Issue by CaptainStabs** [microsoft/Deep3DFaceReconstruction#108]
Haven't seen any issues on this as of yet, so I figured it was time to open one. Lots of faces trigger this error, and I'm not entirely sure why. Any help greatly appreciated!

Same error referenced in #85 

```
Traceback (most recent call last):   File "demo.py", line 123, in <module>
demo                                              File "demo.py", line 104, in demo                                                     
face_shape,face_texture,face_color,landmarks_2d,recon_img,tri],feed_dict = {images: input_img})
File "C:\Users\USER\miniconda3\envs\sisr\lib\site-packages\tensorflow\python\client\session.py", line 929, in run
run_metadata_ptr)                                                                           File "C:\Users\USER\miniconda3\envs\sisr\lib\site-
packages\tensorflow\python\client\session.py", line 1128, in _run
str(subfeed_t.get_shape())))                                                              ValueError: Cannot feed value of shape (1, 224, 224, 4) for Tensor 'input_imgs:0', which has shape '(1, 224, 224, 3)

```

**Comment by YuDeng** [comment]
You have to make sure the input image has 3 channels (RGB) instead of 4 (RGBA). Some images with '.png' extension might have an extra alpha channel. Our model only receives images with 3 channels without the alpha channel.
