### ISSUE TITLE
ValueError: Camera_position must have shape [batch_size, 3]

### ISSUE THREAD

**Issue by SanjunLiu** [microsoft/Deep3DFaceReconstruction#109]
Traceback (most recent call last):
  File "demo.py", line 123, in <module>
    demo()
  File "demo.py", line 81, in demo
    FaceReconstructor.Reconstruction_Block(coeff,opt)
  File "/workspace/dl/Deep3DFaceReconstruction/face_decoder.py", line 63, in Reconstruction_Block
    render_imgs,img_mask,img_mask_crop = self.Render_block(face_shape_t,norm_r,face_color,camera_scale,f_scale,self.facemodel,opt.batch_size,opt.is_train)
  File "/workspace/dl/Deep3DFaceReconstruction/face_decoder.py", line 311, in Render_block
    ambient_color = ambient_color)
  File "/workspace/dl/Deep3DFaceReconstruction/renderer/mesh_renderer.py", line 301, in mesh_renderer
    raise ValueError('Camera_position must have shape [batch_size, 3]')
ValueError: Camera_position must have shape [batch_size, 3]

**Comment by YuDeng** [comment]
This error is related to the tf mesh renderer. Did you use the pre-compiled rasterize_triangles_kernel.so in this repository?

**Comment by fgh-hgf** [comment]
I have the same problem with you. And I fix it by changing "tf.shape(coeff)[0]" to "coeff.shape[0]" in 88 line in face_decoder.py
