### ISSUE TITLE
Error in running the python demo.py

### ISSUE THREAD

**Issue by Iswarya05** [microsoft/Deep3DFaceReconstruction#139]
When i am running the command as "python demo.py" the below error has been displayed.

2021-03-22 17:11:28.867587: I tensorflow/stream_executor/platform/default/dso_loader.cc:49] Successfully opened dynamic library libcudart.so.11.0
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING:root:Limited tf.compat.v2.summary API due to missing TensorBoard installation.
WARNING:root:Limited tf.summary API due to missing TensorBoard installation.
Traceback (most recent call last):
  File "demo.py", line 12, in <module>
    from face_decoder import Face3D
  File "/home/preksh/tf_mesh_renderer/Deep3DFaceReconstruction/face_decoder.py", line 10, in <module>
    from renderer import mesh_renderer
  File "/home/preksh/tf_mesh_renderer/Deep3DFaceReconstruction/renderer/mesh_renderer.py", line 25, in <module>
    from renderer import rasterize_triangles
  File "/home/preksh/tf_mesh_renderer/Deep3DFaceReconstruction/renderer/rasterize_triangles.py", line 30, in <module>
    rasterize_triangles_module = tf.load_op_library('./renderer/rasterize_triangles_kernel.so')
  File "/home/preksh/.conda/envs/deep3d/lib/python3.6/site-packages/tensorflow/python/framework/load_library.py", line 57, in load_op_library
    lib_handle = py_tf.TF_LoadLibrary(library_filename)
tensorflow.python.framework.errors_impl.NotFoundError: libtensorflow_framework.so: cannot open shared object file: No such file or directory.

**Comment by fisakhan** [comment]
I solved this problem by installing TensorFlow C API from `https://www.tensorflow.org/install/lang_c` because tf.load_op_library requires libtensorflow_framework.so

but

now I get the following error:
`NotFoundError: ./renderer/rasterize_triangles_kernel.so: undefined symbol: _ZN10tensorflow15TensorShapeBaseINS_11TensorShapeEEC1EN4absl4SpanIKxEE`

**Comment by TejaswiniiB** [comment]
Hi Im also getting the same error, even if I set `-D_GLIBCXX_USE_CXX11_ABI=1` . How to solve it?
