### ISSUE TITLE
KeyError: 'TEST_SRCDIR'

### ISSUE THREAD

**Issue by UestcJay** [microsoft/Deep3DFaceReconstruction#191]
I follow the instruction, pip tf1.12 on ubuntu16.04, cuda9.0, using the precompiling binary file, but there is a error, can you give me some help?
Traceback (most recent call last):
  File "demo.py", line 13, in <module>
    from face_decoder import Face3D
  File "/root/shenzhen/lkq/Deep3DFaceReconstruction/face_decoder.py", line 10, in <module>
    from renderer import mesh_renderer
  File "/root/shenzhen/lkq/Deep3DFaceReconstruction/renderer/mesh_renderer.py", line 23, in <module>
    import rasterize_triangles
  File "/root/shenzhen/lkq/Deep3DFaceReconstruction/renderer/../renderer/rasterize_triangles.py", line 27, in <module>
    os.path.join(os.environ['TEST_SRCDIR'],
  File "/root/anaconda3/envs/deep3d/lib/python3.6/os.py", line 669, in __getitem__
    raise KeyError(key) from None
KeyError: 'TEST_SRCDIR'

**Comment by Liuxiaoan1** [comment]
我最近也遇到了这个问题  我解决了 如果你是linux则把TEST_SRCDIR改成HOME，下一行改成你的.so文件路径即可，你可以试一下

**Comment by kun2001github** [comment]
I had the same problem, and here's my solution：`export TEST_SRCDIR=/root/Deep3DFaceReconstruction/renderer`
If you want to make it permanent, you can write it to ~/.bashrc
I hope this will help you

Refer to ：https://github.com/tensorflow/tensorflow/issues/8921#issuecomment-291244714
