### ISSUE TITLE
colab practice code plz

### ISSUE THREAD

**Issue by fovekorea** [microsoft/Deep3DFaceReconstruction#70]
I don't know how to set the environment.
So I want you to write it so that you can practice with colab.
Is it possible?

**Comment by psmyth94** [comment]
If anybody is still interested: https://colab.research.google.com/drive/1oWjgftAf6e_yWvgZoXPLhF0UldfHg_Bt?usp=sharing.

**Comment by molo32** [comment]
good job, but how can i download the texture

**Comment by kakao014** [comment]
> If anybody is still interested: https://colab.research.google.com/drive/1oWjgftAf6e_yWvgZoXPLhF0UldfHg_Bt?usp=sharing.

Very thanks, but  there is an erro:

**Comment by kakao014** [comment]
> If anybody is still interested: https://colab.research.google.com/drive/1oWjgftAf6e_yWvgZoXPLhF0UldfHg_Bt?usp=sharing.

Great thanks, but there is an error: ...... rasterize_triangles_kernel.so: cannot open shared object file: No such file or directory

**Comment by mlevet** [comment]
Same error here

**Comment by mlevet** [comment]
@kakao014
Check this : https://github.com/microsoft/Deep3DFaceReconstruction/issues/101

```
if not is_windows:
	import mesh_renderer
```

in face_decoder.py seems to work

**Comment by mlevet** [comment]
rasterize_triangles_kernel.so error disappeared after i replaced renderer by mesh_renderer in face_decoder.py  (https://github.com/microsoft/Deep3DFaceReconstruction/issues/101) but i'm now facing a new EOF error : 
```
Traceback (most recent call last):
  File "demo.py", line 124, in <module>
    demo()
  File "demo.py", line 54, in demo
    transferBFM09()
  File "/content/Deep3DFaceReconstruction/utils.py", line 36, in transferBFM09
    expPC,expEV = LoadExpBasis()
  File "/content/Deep3DFaceReconstruction/utils.py", line 15, in LoadExpBasis
    expMU.fromfile(Expbin,3*n_vertex)
EOFError: read() didn't return enough bytes
```
