### ISSUE TITLE
Error with BFM model

### ISSUE THREAD

**Issue by NabHamzah** [microsoft/Deep3DFaceReconstruction#96]
Hi,
I'm a new comer in deep learning. Just want to try this project but I got an error. Do I have to install Matlab to run this code?
As attached is the error that I got.

Traceback (most recent call last):
  File "demo.py", line 76, in <module>
    demo()
  File "demo.py", line 29, in demo
    transferBFM09()
  File "E:\Deep3DFaceReconstruction-master\load_data.py", line 41, in transferBFM09
    original_BFM = loadmat('BFM/01_MorphableModel.mat')
  File "C:\Users\liza\Anaconda3\envs\tf_gpu\lib\site-packages\scipy\io\matlab\mio.py", line 207, in loadmat
    MR, file_opened = mat_reader_factory(file_name, appendmat, **kwargs)
  File "C:\Users\liza\Anaconda3\envs\tf_gpu\lib\site-packages\scipy\io\matlab\mio.py", line 63, in mat_reader_factory
    mjv, mnv = get_matfile_version(byte_stream)
  File "C:\Users\liza\Anaconda3\envs\tf_gpu\lib\site-packages\scipy\io\matlab\miobase.py", line 241, in get_matfile_version
    raise ValueError('Unknown mat file type, version %s, %s' % ret)
ValueError: Unknown mat file type, version 0, 0

**Comment by hoangtdTcom** [comment]
can you give me the tf_mesh_renderer / mesh_renderer / kernels / rasterize_triangles_kernel.so file?

**Comment by YuDeng** [comment]
It seems that your scipy's version is incompatible with the 01_MorphableModel.mat. You could try other versions to see if it works. Everything should work without matlab.
